/**
 * Mock Data & Constants — InStockInvoicePage
 *
 * ⚠️  Khi tích hợp backend, thay thế các mảng dưới đây
 *     bằng API service calls.
 *     Ví dụ: WOOD_PRODUCTS → productApi.getWoodProducts()
 *
 * Created By: DNC
 * Created Date: 25/02/2026
 */

// ===================== CONSTANTS =====================
export const SYSTEM_WARRANTY = "12 tháng"; // Cấu hình bảo hành từ hệ thống
export const ITEMS_PER_PAGE = 15;

export const CATEGORIES = [
  "Phòng khách",
  "Phòng ngủ",
  "Phòng ăn",
  "Phòng làm việc",
  "Quà tặng",
];

// ===================== HELPERS =====================
export const fmt = (v) => new Intl.NumberFormat("vi-VN").format(v);

let tabIdCounter = 1;
export const createEmptyTab = () => ({
  id: ++tabIdCounter,
  cartItems: [],
  selectedCustomer: null,
  orderNote: "",
  discount: 0,
  depositAmount: 0,
  deliveryMethod: "store", // "store" hoặc "delivery"
  deliveryDate: "",
  storePickupDate: "", // yyyy-mm-dd — để trống = lấy ngay, có ngày = hẹn lấy
});

// ===================== MOCK PRODUCTS =====================
export const WOOD_PRODUCTS = [
  {
    id: 1,
    name: "Bộ bàn ăn gỗ sồi 4 ghế",
    sku: "BA-SOI-4G",
    price: 12500000,
    discount: 10,
    stock: 8,
    image: "/wood_products.png",
    category: "Phòng ăn",
    productType: "Hàng sẵn",
    color: "Sồi tự nhiên",
    leadTime: 0,
    description: "Bộ bàn ăn 6 ghế chất liệu gỗ sồi Nga tự nhiên, xử lý chống mối mọt, thiết kế hiện đại phù hợp cho phòng ăn gia đình. Kích thước (Bàn): 180 x 90 x 75 cm.",
  },
  {
    id: 2,
    name: "Kệ sách gỗ óc chó 5 tầng",
    sku: "KS-OC-5T",
    price: 8900000,
    stock: 5,
    image: "/wood_products.png",
    category: "Phòng làm việc",
    productType: "Hàng sẵn",
    color: "Óc chó đậm",
    leadTime: 0,
    description: "Kệ sách 5 tầng bền bỉ, vân gỗ óc chó sang trọng, tạo điểm nhấn cho không gian làm việc hoặc phòng khách. Kích thước: 120 x 35 x 180 cm.",
  },
  {
    id: 3,
    name: "Bàn làm việc gỗ sồi 3 ngăn",
    sku: "BLV-SOI-3N",
    price: 7200000,
    discount: 12,
    stock: 12,
    image: "/wood_products.png",
    category: "Phòng làm việc",
    productType: "Hàng mộc",
    color: "Trắng sồi",
    leadTime: 7,
    description: "Bàn làm việc sơn trắng sồi thanh lịch, tích hợp 3 ngăn kéo tiện lợi cho việc lưu trữ hồ sơ, văn phòng phẩm. Kích thước: 140 x 70 x 75 cm.",
  },
  {
    id: 4,
    name: "Tủ đựng đồ gỗ óc chó",
    sku: "TDD-OC-01",
    price: 9800000,
    stock: 3,
    image: "/wood_products.png",
    category: "Phòng ngủ",
    productType: "Hàng mộc",
    color: "Nguyên mộc",
    leadTime: 7,
    description: "Kích thước: 100 x 45 x 120 cm.",
  },
  {
    id: 5,
    name: "Ghế ăn gỗ sồi tự nhiên",
    sku: "GA-SOI-TN",
    price: 1850000,
    stock: 25,
    image: "/wood_products.png",
    category: "Phòng ăn",
    productType: "Hàng sẵn",
    color: "Sồi sáng",
    description: "Kích thước: 45 x 48 x 90 cm.",
  },
  {
    id: 6,
    name: "Bàn trà đôi mặt đá Marble",
    sku: "BT-MD-06",
    price: 4200000,
    discount: 15,
    stock: 8,
    image: "/wood_products.png",
    category: "Phòng khách",
    productType: "Hàng sẵn",
    color: "Trắng vân mây",
    description: "Kích thước mặt bàn: D80 & D60 cm.",
  },
  {
    id: 7,
    name: "Tủ rượu góc gỗ hương",
    sku: "TR-HU-07",
    price: 8900000,
    stock: 0,
    image: "/wood_products.png",
    category: "Phòng khách",
    productType: "Hàng mộc",
    description: "Kích thước: Cao 220 cm.",
  },
  {
    id: 8,
    name: "Vách ngăn lam gỗ trang trí",
    sku: "VN-LG-08",
    price: 2500000,
    stock: 15,
    image: "/wood_products.png",
    category: "Phòng khách",
    productType: "Hàng sẵn",
    color: "Nâu cà phê",
    description: "Kích thước: Module 100 x 240 cm.",
  },
  {
    id: 9,
    name: "Sofa nỉ chữ L cỡ lớn",
    sku: "SF-NL-09",
    price: 15800000,
    discount: 5,
    stock: 4,
    image: "/wood_products.png",
    category: "Phòng khách",
    productType: "Hàng sẵn",
    color: "Xanh Navy",
    description: "Kích thước: 280 x 160 cm.",
  },
  {
    id: 10,
    name: "Tủ giày gỗ thông ghép",
    sku: "TG-GT-10",
    price: 1200000,
    discount: 10,
    stock: 30,
    image: "/wood_products.png",
    category: "Phòng khách",
    productType: "Hàng mộc",
    color: "Nguyên mộc",
    description: "Kích thước: 80 x 120 x 30 cm.",
  },
  {
    id: 11,
    name: "Tủ giày MDF phủ Melamine",
    sku: "TG-MDF-11",
    price: 1850000,
    stock: 18,
    image: "/wood_products.png",
    category: "Phòng khách",
    productType: "Hàng sẵn",
    color: "Trắng + Vân gỗ",
    description: "Kích thước: 100 x 110 x 35 cm.",
  },
  {
    id: 12,
    name: "Bàn console gỗ óc chó",
    sku: "BC-OC-01",
    price: 6800000,
    stock: 7,
    image: "/wood_products.png",
    category: "Phòng khách",
    productType: "Hàng sẵn",
    color: "Cánh gián nhạt",
    description: "Kích thước: 140 x 40 x 85 cm.",
  },
  {
    id: 13,
    name: "Sofa da thật góc L chữ U",
    sku: "SF-DA-13",
    price: 25000000,
    stock: 3,
    image: "/wood_products.png",
    category: "Phòng khách",
    productType: "Hàng sẵn",
    color: "Đen tuyền",
    description: "Kích thước: 320 x 200 cm.",
  },
  {
    id: 14,
    name: "Bàn trà đôi mặt kính khung sắt",
    sku: "BT-K-14",
    price: 3200000,
    stock: 15,
    image: "/wood_products.png",
    category: "Phòng khách",
    productType: "Hàng sẵn",
    color: "Đen mờ",
    description: "Kích thước: Tròn 70 cm.",
  },
  {
    id: 15,
    name: "Kệ TV treo tường tối giản",
    sku: "KTV-TT-15",
    price: 4100000,
    stock: 20,
    image: "/wood_products.png",
    category: "Phòng khách",
    productType: "Hàng sẵn",
    color: "Xám chì",
    description: "Kích thước: 180 x 35 cm.",
  },
  {
    id: 16,
    name: "Tủ giày thông minh 3 tầng",
    sku: "TG-TM-16",
    price: 2800000,
    stock: 12,
    image: "/wood_products.png",
    category: "Phòng khách",
    productType: "Hàng sẵn",
    color: "Vân sồi",
    description: "Kích thước: 90 x 120 x 24 cm.",
  },
  {
    id: 17,
    name: "Ghế đôn sofa bọc nhung",
    sku: "GD-BN-17",
    price: 850000,
    stock: 30,
    image: "/wood_products.png",
    category: "Phòng khách",
    productType: "Hàng mộc",
    description: "Kích thước: Tròn 40 cm.",
  },
  {
    id: 18,
    name: "Vách ngăn phòng khách cnc",
    sku: "VN-CNC-18",
    price: 5600000,
    stock: 5,
    image: "/wood_products.png",
    category: "Phòng khách",
    productType: "Hàng mộc",
    description: "Kích thước: Module 120x260 cm.",
  },

  // Phòng ngủ
  {
    id: 19,
    name: "Giường bọc da đầu giường cao",
    sku: "GBD-19",
    price: 18500000,
    discount: 7,
    stock: 4,
    image: "/wood_products.png",
    category: "Phòng ngủ",
    productType: "Hàng mộc",
    description: "Kích thước lọt lòng: 180 x 200 cm.",
  },
  {
    id: 20,
    name: "Tủ quần áo cánh lùa kính đen",
    sku: "TQA-L-20",
    price: 21000000,
    discount: 8,
    stock: 2,
    image: "/wood_products.png",
    category: "Phòng ngủ",
    productType: "Hàng sẵn",
    color: "Khung đen",
    description: "Kích thước: 240 x 220 x 60 cm.",
  },
  {
    id: 21,
    name: "Bàn trang điểm gương LED",
    sku: "BTD-LED-21",
    price: 5400000,
    stock: 8,
    image: "/wood_products.png",
    category: "Phòng ngủ",
    productType: "Hàng sẵn",
    color: "Trắng sứ",
    description: "Kích thước: 100 x 40 x 75 cm.",
  },
  {
    id: 22,
    name: "Tab đầu giường gỗ tự nhiên",
    sku: "TDG-TN-22",
    price: 1200000,
    stock: 25,
    image: "/wood_products.png",
    category: "Phòng ngủ",
    productType: "Hàng sẵn",
    color: "Sơn bóng mờ",
    description: "Kích thước: 45 x 40 x 45 cm.",
  },
  {
    id: 23,
    name: "Giường tầng trẻ em gỗ thông",
    sku: "GT-TE-23",
    price: 9500000,
    stock: 6,
    image: "/wood_products.png",
    category: "Phòng ngủ",
    productType: "Hàng mộc",
    description: "Kích thước tầng: 120 x 200 cm.",
  },
  {
    id: 24,
    name: "Ghế thư giãn đọc sách kèm đôn",
    sku: "GTG-24",
    price: 6200000,
    stock: 10,
    image: "/wood_products.png",
    category: "Phòng ngủ",
    productType: "Hàng sẵn",
    color: "Ghi sáng",
    description: "Kích thước Ghế: 85x85 cm. Kích thước Đôn: 50x40 cm.",
  },
  {
    id: 25,
    name: "Tủ ngăn kéo để đồ mini",
    sku: "TNK-25",
    price: 3100000,
    stock: 14,
    image: "/wood_products.png",
    category: "Phòng ngủ",
    productType: "Hàng mộc",
    description: "Kích thước: 60 x 80 x 40 cm.",
  },
  {
    id: 26,
    name: "Giá treo quần áo khung thép",
    sku: "GTQA-26",
    price: 950000,
    stock: 40,
    image: "/wood_products.png",
    category: "Phòng ngủ",
    productType: "Hàng mộc",
    description: "Kích thước: 150 x 40 cm.",
  },

  // Phòng ăn
  {
    id: 27,
    name: "Bộ bàn ăn mặt đá ceramic",
    sku: "BCC-27",
    price: 17800000,
    stock: 5,
    image: "/wood_products.png",
    category: "Phòng ăn",
    productType: "Hàng sẵn",
    color: "Mặt đá xám vân xoáy",
    description: "Kích thước bàn: 160 x 80 cm.",
  },
  {
    id: 28,
    name: "Tủ lạnh âm tủ đa năng",
    sku: "TCA-28",
    price: 12500000,
    stock: 3,
    image: "/wood_products.png",
    category: "Phòng ăn",
    productType: "Hàng sẵn",
    color: "Đen nhám",
    description: "Kích thước: Module 60x60x220 cm.",
  },
  {
    id: 29,
    name: "Tủ bếp acrylic bóng gương",
    sku: "TBAC-29",
    price: 28000000,
    stock: 1,
    image: "/wood_products.png",
    category: "Phòng ăn",
    productType: "Hàng sẵn",
    color: "Xanh ngọc / Trắng",
    description: "Kích thước tủ bếp: Theo mặt bằng thực tế.",
  },
  {
    id: 30,
    name: "Ghế ăn bọc da PU cao cấp",
    sku: "GAAP-30",
    price: 1450000,
    stock: 50,
    image: "/wood_products.png",
    category: "Phòng ăn",
    productType: "Hàng sẵn",
    color: "Da bò",
    description: "Sản phẩm ghế chân cao 45cm.",
  },
  {
    id: 31,
    name: "Đảo bếp di động mặt gỗ",
    sku: "DB-31",
    price: 8900000,
    discount: 15,
    stock: 7,
    image: "/wood_products.png",
    category: "Phòng ăn",
    productType: "Hàng mộc",
    description: "Kích thước mặt đảo: 120 x 80 cm.",
  },
  {
    id: 32,
    name: "Kệ để rượu treo tường",
    sku: "KDR-32",
    price: 2100000,
    stock: 18,
    image: "/wood_products.png",
    category: "Phòng ăn",
    productType: "Hàng sẵn",
    color: "Nâu cánh gián",
    description: "Kích thước: 80 x 110 x 20 cm.",
  },
  {
    id: 33,
    name: "Bàn ăn tròn xoay thông minh",
    sku: "BAT-33",
    price: 15600000,
    stock: 4,
    image: "/wood_products.png",
    category: "Phòng ăn",
    productType: "Hàng sẵn",
    color: "Mặt đá vân mây trắng",
    description: "Kích thước bàn xoay: Đường kính 1.4m.",
  },

  // Phòng làm việc
  {
    id: 34,
    name: "Ghế công thái học Ergonomic",
    sku: "GCTH-34",
    price: 4500000,
    discount: 20,
    stock: 22,
    image: "/wood_products.png",
    category: "Phòng làm việc",
    productType: "Hàng sẵn",
    color: "Đen / Trắng xám",
    description: "Kích thước: Tiêu chuẩn Adult.",
  },
  {
    id: 35,
    name: "Bàn nâng hạ chiều cao điện",
    sku: "BNH-35",
    price: 8200000,
    stock: 9,
    image: "/wood_products.png",
    category: "Phòng làm việc",
    productType: "Hàng sẵn",
    color: "Mặt óc chó / Chân đen",
    description: "Kích thước mặt bàn: 160 x 75 cm.",
  },
  {
    id: 36,
    name: "Tủ hồ sơ văn phòng 2 cánh",
    sku: "THS-36",
    price: 3600000,
    stock: 16,
    image: "/wood_products.png",
    category: "Phòng làm việc",
    productType: "Hàng sẵn",
    color: "Ghi chì",
    description: "Kích thước: 120 x 200 x 40 cm.",
  },
  {
    id: 37,
    name: "Kệ máy in để bàn",
    sku: "KMI-37",
    price: 650000,
    stock: 35,
    image: "/wood_products.png",
    category: "Phòng làm việc",
    productType: "Hàng mộc",
    description: "Kích thước: 50 x 40 x 30 cm.",
  },
  {
    id: 38,
    name: "Ghế xoay lưới văn phòng",
    sku: "GXV-38",
    price: 1850000,
    stock: 45,
    image: "/wood_products.png",
    category: "Phòng làm việc",
    productType: "Hàng sẵn",
    color: "Đen",
    description: "Tải trọng cao. Kích thước: Size L.",
  },
  {
    id: 39,
    name: "Hộc tủ di động 3 ngăn kéo",
    sku: "HT-39",
    price: 1550000,
    stock: 28,
    image: "/wood_products.png",
    category: "Phòng làm việc",
    productType: "Hàng mộc",
    color: "Gỗ thông mộc",
    description: "Kích thước: 50 x 40 x 30 cm.",
  },
  {
    id: 40,
    name: "Bàn họp chân sắt chữ U",
    sku: "BHC-40",
    price: 9800000,
    stock: 5,
    image: "/wood_products.png",
    category: "Phòng làm việc",
    productType: "Hàng sẵn",
    color: "Vàng vân gỗ / Chân ghi",
    description: "Kích thước bàn họp lớn: 240 x 120 x 75 cm.",
  },
];

// ===================== MOCK GIFTS =====================
export const GIFT_PRODUCTS = [
  {
    id: 1001,
    name: "Gối tựa lưng Sofa họa tiết",
    sku: "QT-GOI-01",
    price: 0,
    stock: 50,
    image: "/wood_products.png",
    category: "Quà tặng",
    productType: "Quà tặng",
    color: "Họa tiết Vintage",
    description:
      "Gối tựa lưng êm ái với họa tiết Vintage độc đáo, mang lại sự thoải mái và vẻ đẹp cổ điển cho bộ sofa nhà bạn. Kích thước: 45x45 cm.",
  },
  {
    id: 1002,
    name: "Khăn trải bàn ren cao cấp",
    sku: "QT-KHAN-02",
    price: 0,
    stock: 30,
    image: "/wood_products.png",
    category: "Quà tặng",
    productType: "Quà tặng",
    color: "Trắng kem",
    description: "Kích thước khăn: 140x180 cm.",
  },
  {
    id: 1003,
    name: "Bộ vệ sinh gỗ chuyên dụng",
    sku: "QT-VS-03",
    price: 0,
    stock: 100,
    image: "/wood_products.png",
    category: "Quà tặng",
    productType: "Quà tặng",
    color: "Trong suốt",
    description: "Chai dung tích 500ml.",
  },
  {
    id: 1004,
    name: "Lót ly gỗ bần (Bộ 6 cái)",
    sku: "QT-LOT-04",
    price: 0,
    stock: 40,
    image: "/wood_products.png",
    category: "Quà tặng",
    productType: "Quà tặng",
    color: "Nâu bần",
    description: "Kích thước lót ly: D10 cm.",
  },
];

// ===================== MOCK CUSTOMERS =====================
export const MOCK_CUSTOMERS = [
  {
    id: 1,
    name: "Nguyễn Văn Hoàng",
    phone: "0901234567",
    address: "123 Giải Phóng, Hai Bà Trưng, Hà Nội",
  },
  {
    id: 2,
    name: "Trần Thị Mai",
    phone: "0912345678",
    address: "456 Kim Mã, Ba Đình, Hà Nội",
  },
  {
    id: 3,
    name: "Lê Minh Tuấn",
    phone: "0923456789",
    address: "789 Nguyễn Trãi, Thanh Xuân, Hà Nội",
  },
  {
    id: 4,
    name: "Phạm Thị Lan",
    phone: "0934567890",
    address: "321 Lạc Long Quân, Tây Hồ, Hà Nội",
  },
  {
    id: 5,
    name: "Võ Đức Anh",
    phone: "0945678901",
    address: "654 Minh Khai, Hai Bà Trưng, Hà Nội",
  },
  {
    id: 6,
    name: "Đặng Thùy Linh",
    phone: "0956789012",
    address: "987 Cầu Giấy, Cầu Giấy, Hà Nội",
  },
  {
    id: 7,
    name: "Bùi Tuấn Anh",
    phone: "0967890123",
    address: "159 Đội Cấn, Ba Đình, Hà Nội",
  },
  {
    id: 8,
    name: "Hoàng Nguyệt Ánh",
    phone: "0978901234",
    address: "753 Lê Duẩn, Hoàn Kiếm, Hà Nội",
  },
  {
    id: 9,
    name: "Đinh Quang Hiếu",
    phone: "0989012345",
    address: "246 Bà Triệu, Hoàn Kiếm, Hà Nội",
  },
  {
    id: 10,
    name: "Vũ Phương Thảo",
    phone: "0990123456",
    address: "135 Trần Duy Hưng, Cầu Giấy, Hà Nội",
  },
];
